version: '3'

services:
  batch:
    command: python -u /app/src/sps_schedule.py
    build:
      context: .
      dockerfile: ./docker/sps/Dockerfile
    volumes:
      - ./sps.db:/app/sps.db
    networks:
      - sps-net
  api:
    command: python /app/src/sps_api.py
    build:
      context: .
      dockerfile: ./docker/sps/Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    networks:
      - sps-net
  monitor:
    ports:
      # - 3000:3000
      - 8080:80
    build:
      context: .
      dockerfile: ./docker/monitor/Dockerfile
    volumes:
      - .:/app
      - ./log/nginx:/var/log/nginx
      - ./nginx:/etc/nginx/conf.d
    networks:
      - sps-net

networks:
  sps-net:
    driver: bridge
