version: '3'

services:
  batch:
    command: python -u /app/src/sps_schedule.py
    build:
      context: .
      dockerfile: ./docker/sps/Dockerfile
    volumes:
      - .:/app
    networks:
      - sps-net
  api:
    command: python /app/src/sps_api.py
    build:
      context: .
      dockerfile: ./docker/sps/Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    networks:
      - sps-net
  monitor:
    build:
      context: .
      dockerfile: ./docker/monitor/Dockerfile
    volumes:
      - .:/app
    networks:
      - sps-net

networks:
  sps-net:
    driver: bridge
