name: sps ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2 
      - name: setup environment
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install pipenv --system
        run: |
          pipenv install --system
      - name: Run migrate
        run: |
          python src/sps_cmd.py migrate
        env:
          DATABASE_URL: sqlite:///./sps.db
      - name: Run pytest
        run: |
          pipenv run test